/content/documents/gogreen/products:
  .meta:order-before: newsfacets
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 6d1e0487-bc6a-40bd-ac3d-83ebe9b451a5
  hippostd:foldertype: [new-product-folder, new-product-document]
  hippotranslation:id: 7e838308-62d1-4cd0-b8e9-a9e58dcca1e1
  hippotranslation:locale: en
  /solar-centurian---outdoor-security-light:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'mix:referenceable']
    jcr:uuid: bd8e53a1-9083-49a8-922b-4c4f0875d4ab
    hippo:name: Solar Centurian - Outdoor Security Light
    /solar-centurian---outdoor-security-light[1]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: a3705d7a-8d1b-4410-b135-f2a87b91e84f
      gogreen:introduction: Light up your night with a solar powered, motion detected
        outdoor security light!
      gogreen:price: 74.0
      gogreen:title: Solar Centurian - Outdoor Security Light
      hippo:availability: []
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2018-08-21T15:17:51.351-07:00
      hippostdpubwf:lastModificationDate: 2018-08-21T15:17:51.351-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 23371bf7-72a8-44ed-a3ef-e21884aae901
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>This solar powered light is a bright (over 600 lumen) Halogen Security Light that installs easily where utility wiring is impractical or expensive. A patented passive infrared motion detector is able to detect activity up to 23m/75 feet away controls the light. When activated, the Solar Centurion throws a flood light into the target area for up to 3 minutes or as long as there is movement in the area.</p>

          <p>It is perfect for security lighting or convenience lighting in your yard, at your garage, around your garage, or wherever security lighting is required at night!</p>

          <p>The light is replaceable at any lighting or hardware store (Sylvania 1995/ERK miniature Halogen Lamp).</p>

          <p>© Green Home, Inc.<br />
          <a href="http://www.greenhome.com/products/yard_and_garden/outdoor_lighting/109508/">http://www.greenhome.com/products/yard_and_garden/outdoor_lighting/109508/</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 73aad92f-5574-4e4e-9414-9695f7214542
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /solar-centurian---outdoor-security-light[2]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: 72a1bc0b-0658-45dc-ae5f-2442850a0fc8
      gogreen:introduction: Light up your night with a solar powered, motion detected
        outdoor security light!
      gogreen:price: 74.0
      gogreen:title: Solar Centurian - Outdoor Security Light
      hippo:availability: [preview]
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2018-08-21T15:17:51.351-07:00
      hippostdpubwf:lastModificationDate: 2018-08-21T15:18:36.271-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 23371bf7-72a8-44ed-a3ef-e21884aae901
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>This solar powered light is a bright (over 600 lumen) Halogen Security Light that installs easily where utility wiring is impractical or expensive. A patented passive infrared motion detector is able to detect activity up to 23m/75 feet away controls the light. When activated, the Solar Centurion throws a flood light into the target area for up to 3 minutes or as long as there is movement in the area.</p>

          <p>It is perfect for security lighting or convenience lighting in your yard, at your garage, around your garage, or wherever security lighting is required at night!</p>

          <p>The light is replaceable at any lighting or hardware store (Sylvania 1995/ERK miniature Halogen Lamp).</p>

          <p>© Green Home, Inc.<br />
          <a href="http://www.greenhome.com/products/yard_and_garden/outdoor_lighting/109508/">http://www.greenhome.com/products/yard_and_garden/outdoor_lighting/109508/</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 73aad92f-5574-4e4e-9414-9695f7214542
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /solar-centurian---outdoor-security-light[3]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 355ac5fe-f232-47a0-aec0-00d41b0c2ed1
      gogreen:introduction: Light up your night with a solar powered, motion detected
        outdoor security light!
      gogreen:price: 74.0
      gogreen:title: Solar Centurian - Outdoor Security Light
      hippo:availability: [live]
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2018-08-21T15:17:51.351-07:00
      hippostdpubwf:lastModificationDate: 2018-08-21T15:18:36.271-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2018-08-21T15:18:39.993-07:00
      hippotranslation:id: 23371bf7-72a8-44ed-a3ef-e21884aae901
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>This solar powered light is a bright (over 600 lumen) Halogen Security Light that installs easily where utility wiring is impractical or expensive. A patented passive infrared motion detector is able to detect activity up to 23m/75 feet away controls the light. When activated, the Solar Centurion throws a flood light into the target area for up to 3 minutes or as long as there is movement in the area.</p>

          <p>It is perfect for security lighting or convenience lighting in your yard, at your garage, around your garage, or wherever security lighting is required at night!</p>

          <p>The light is replaceable at any lighting or hardware store (Sylvania 1995/ERK miniature Halogen Lamp).</p>

          <p>© Green Home, Inc.<br />
          <a href="http://www.greenhome.com/products/yard_and_garden/outdoor_lighting/109508/">http://www.greenhome.com/products/yard_and_garden/outdoor_lighting/109508/</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 73aad92f-5574-4e4e-9414-9695f7214542
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
  /lifeproof-nuud-ipad-air-case:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'mix:referenceable']
    jcr:uuid: 67b750ce-519e-4309-a00e-228d51ce3f57
    hippo:name: Lifeproof nüüd IPad Air Case
    /lifeproof-nuud-ipad-air-case[1]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 2e48f5cd-c400-44d7-849f-a9e366145a1c
      gogreen:introduction: Get full protection for your phone in any wet, dirty or
        damp setting.The nuud case armours your iPad Air without putting anything
        between your fingertips and the touchscreen. An optical glass lens lets you
        see and use the screen with crystal clarity.
      gogreen:price: 129.0
      gogreen:title: Lifeproof nüüd IPad Air Case
      hippo:availability: []
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2018-08-21T15:20:56.853-07:00
      hippostdpubwf:lastModificationDate: 2018-08-21T15:20:56.853-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: edd85d7d-03f0-41ae-b119-b5c5d36cb6da
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Waterproof, fully submersible to 2 metres for up to 1 hour.</li>
           <li>Shockproof, survives drops from 2 metres.</li>
           <li>Full access to touchscreen and all buttons, ports and controls.</li>
           <li>Maximum sound output and clarity.</li>
           <li>Anti-reflective optical-glass camera lens.</li>
           <li>Dimensions are 261.6 x 188 x 17.8mm.</li>
           <li>The LifeProof warranty and MEC's Rocksolid Guarantee cover this case itself. Neither guarantee covers the contents you put inside the case.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023">http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 1435c19c-12eb-4dbc-ab00-a4d5c64e8254
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /lifeproof-nuud-ipad-air-case[2]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: de78e6f1-b0bd-49c5-9dc7-f84123701859
      gogreen:introduction: Get full protection for your phone in any wet, dirty or
        damp setting.The nuud case armours your iPad Air without putting anything
        between your fingertips and the touchscreen. An optical glass lens lets you
        see and use the screen with crystal clarity.
      gogreen:price: 129.0
      gogreen:title: Lifeproof nüüd IPad Air Case
      hippo:availability: [preview]
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2018-08-21T15:20:56.853-07:00
      hippostdpubwf:lastModificationDate: 2018-08-21T15:21:46.446-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: edd85d7d-03f0-41ae-b119-b5c5d36cb6da
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Waterproof, fully submersible to 2 metres for up to 1 hour.</li>
           <li>Shockproof, survives drops from 2 metres.</li>
           <li>Full access to touchscreen and all buttons, ports and controls.</li>
           <li>Maximum sound output and clarity.</li>
           <li>Anti-reflective optical-glass camera lens.</li>
           <li>Dimensions are 261.6 x 188 x 17.8mm.</li>
           <li>The LifeProof warranty and MEC's Rocksolid Guarantee cover this case itself. Neither guarantee covers the contents you put inside the case.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023">http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 1435c19c-12eb-4dbc-ab00-a4d5c64e8254
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /lifeproof-nuud-ipad-air-case[3]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: e532196b-b87c-4c95-93bd-afea57be6024
      gogreen:introduction: Get full protection for your phone in any wet, dirty or
        damp setting.The nuud case armours your iPad Air without putting anything
        between your fingertips and the touchscreen. An optical glass lens lets you
        see and use the screen with crystal clarity.
      gogreen:price: 129.0
      gogreen:title: Lifeproof nüüd IPad Air Case
      hippo:availability: [live]
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2018-08-21T15:20:56.853-07:00
      hippostdpubwf:lastModificationDate: 2018-08-21T15:21:46.446-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2018-08-21T15:21:47.787-07:00
      hippotranslation:id: edd85d7d-03f0-41ae-b119-b5c5d36cb6da
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Waterproof, fully submersible to 2 metres for up to 1 hour.</li>
           <li>Shockproof, survives drops from 2 metres.</li>
           <li>Full access to touchscreen and all buttons, ports and controls.</li>
           <li>Maximum sound output and clarity.</li>
           <li>Anti-reflective optical-glass camera lens.</li>
           <li>Dimensions are 261.6 x 188 x 17.8mm.</li>
           <li>The LifeProof warranty and MEC's Rocksolid Guarantee cover this case itself. Neither guarantee covers the contents you put inside the case.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023">http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 1435c19c-12eb-4dbc-ab00-a4d5c64e8254
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
  /mec-lodge-4-4-tent:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'mix:referenceable']
    jcr:uuid: 7b901086-7f9a-4369-bb2e-f67b27985b0c
    hippo:name: MEC Lodge 4+4 Tent
    /mec-lodge-4-4-tent[1]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 5615164a-3844-4fc2-8eb1-5ead21726738
      gogreen:introduction: Glamping, anyone? This large tent has 2 bedrooms that
        each sleep 2 people. Both rooms are accessed from a central hall that’s tall
        enough to stand up in. The hall doesn't have a floor, so you can use it to
        deal with wet gear without getting your sleeping bags wet or gritty. Store
        your bikes in it, dry your wetsuit, or use it as a sheltered dining area.
        An optional ground sheet converts the hall to a bedroom that sleeps up to
        4 additional campers.
      gogreen:price: 589.0
      gogreen:title: MEC Lodge 4+4 Tent
      hippo:availability: []
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2018-08-21T15:22:06.246-07:00
      hippostdpubwf:lastModificationDate: 2018-08-21T15:22:06.246-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 0c4ddb30-f8a3-42dd-97cd-64a55721a72e
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Central hall has doors with zippable mesh ventilation at either end.</li>
           <li>Hall has numerous hanging points for drying lines or lanterns.</li>
           <li>Each 2-person room has double pockets.</li>
           <li>Hall has 4 storage pockets.</li>
           <li>Optional floor for central hall available separately.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858">http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4a83a3fc-f710-4504-8fce-5cb038acc2a2
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /mec-lodge-4-4-tent[2]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: 4705d9b7-0b86-42d5-a8b8-113e8632a0bc
      gogreen:introduction: Glamping, anyone? This large tent has 2 bedrooms that
        each sleep 2 people. Both rooms are accessed from a central hall that’s tall
        enough to stand up in. The hall doesn't have a floor, so you can use it to
        deal with wet gear without getting your sleeping bags wet or gritty. Store
        your bikes in it, dry your wetsuit, or use it as a sheltered dining area.
        An optional ground sheet converts the hall to a bedroom that sleeps up to
        4 additional campers.
      gogreen:price: 589.0
      gogreen:title: MEC Lodge 4+4 Tent
      hippo:availability: [preview]
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2018-08-21T15:22:06.246-07:00
      hippostdpubwf:lastModificationDate: 2018-08-21T15:23:17.765-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 0c4ddb30-f8a3-42dd-97cd-64a55721a72e
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Central hall has doors with zippable mesh ventilation at either end.</li>
           <li>Hall has numerous hanging points for drying lines or lanterns.</li>
           <li>Each 2-person room has double pockets.</li>
           <li>Hall has 4 storage pockets.</li>
           <li>Optional floor for central hall available separately.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858">http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4a83a3fc-f710-4504-8fce-5cb038acc2a2
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /mec-lodge-4-4-tent[3]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 18433e19-97de-4301-a5ba-a2f945c1b072
      gogreen:introduction: Glamping, anyone? This large tent has 2 bedrooms that
        each sleep 2 people. Both rooms are accessed from a central hall that’s tall
        enough to stand up in. The hall doesn't have a floor, so you can use it to
        deal with wet gear without getting your sleeping bags wet or gritty. Store
        your bikes in it, dry your wetsuit, or use it as a sheltered dining area.
        An optional ground sheet converts the hall to a bedroom that sleeps up to
        4 additional campers.
      gogreen:price: 589.0
      gogreen:title: MEC Lodge 4+4 Tent
      hippo:availability: [live]
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2018-08-21T15:22:06.246-07:00
      hippostdpubwf:lastModificationDate: 2018-08-21T15:23:17.765-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2018-08-21T15:23:19.069-07:00
      hippotranslation:id: 0c4ddb30-f8a3-42dd-97cd-64a55721a72e
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Central hall has doors with zippable mesh ventilation at either end.</li>
           <li>Hall has numerous hanging points for drying lines or lanterns.</li>
           <li>Each 2-person room has double pockets.</li>
           <li>Hall has 4 storage pockets.</li>
           <li>Optional floor for central hall available separately.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858">http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4a83a3fc-f710-4504-8fce-5cb038acc2a2
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
