definitions:
  config:
    /hst:hst/hst:configurations/gogreen/hst:workspace/hst:containers:
      jcr:primaryType: hst:containercomponentfolder
      /base:
        jcr:primaryType: hst:containercomponentfolder
        /top:
          jcr:primaryType: hst:containercomponent
          hst:label: Top
          hst:xtype: hst.vbox
        /footer:
          jcr:primaryType: hst:containercomponent
          hst:label: Footer
          hst:xtype: hst.vbox
      /homepage:
        jcr:primaryType: hst:containercomponentfolder
        /main:
          jcr:primaryType: hst:containercomponent
          hst:label: Home Page Main
          hst:xtype: hst.vbox
      /pagenotfound:
        jcr:primaryType: hst:containercomponentfolder
        /main:
          jcr:primaryType: hst:containercomponent
          hst:label: Page-Not-Found Main
          hst:xtype: hst.vbox
      /newslist:
        jcr:primaryType: hst:containercomponentfolder
        /main:
          jcr:primaryType: hst:containercomponent
          hst:label: News List Main
          hst:xtype: hst.vbox
          /newslist:
            jcr:primaryType: hst:containeritemcomponent
            hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsNewsComponent
            hst:label: News List
            hst:parameternames: [hidePastEvents, documentTypes, sortField, sortOrder,
              includeSubtypes, showPagination, path, pageSize, documentDateField,
              hideFutureItems]
            hst:parametervalues: ['on', 'gogreen:newsdocument', '', desc, 'off', 'on',
              '', '10', 'gogreen:date', 'on']
            hst:template: newslist-main-newslist
            hst:xtype: hst.item
      /newspage:
        jcr:primaryType: hst:containercomponentfolder
        /main:
          jcr:primaryType: hst:containercomponent
          hst:label: News Page Main
          hst:xtype: hst.vbox
          /content:
            jcr:primaryType: hst:containeritemcomponent
            hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsContentComponent
            hst:template: newspage-main
            hst:xtype: hst.item
      /contentlist:
        jcr:primaryType: hst:containercomponentfolder
        /main:
          jcr:primaryType: hst:containercomponent
          hst:label: Content List Main
          hst:xtype: hst.vbox
          /contentlist:
            jcr:primaryType: hst:containeritemcomponent
            hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsListComponent
            hst:label: Content list
            hst:parameternames: [documentTypes, sortField, sortOrder, includeSubtypes,
              showPagination, path, pageSize]
            hst:parametervalues: ['gogreen:contentdocument', '', desc, 'off', 'on',
              '', '10']
            hst:template: contentlist-main-contentlist
            hst:xtype: hst.item
      /contentpage:
        jcr:primaryType: hst:containercomponentfolder
        /main:
          jcr:primaryType: hst:containercomponent
          hst:label: Content Page Main
          hst:xtype: hst.vbox
          /content:
            jcr:primaryType: hst:containeritemcomponent
            hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsContentComponent
            hst:template: contentpage-main
            hst:xtype: hst.item
