definitions:
  config:
    /hst:hst/hst:configurations/gogreen/hst:workspace/hst:sitemap:
      jcr:primaryType: hst:sitemap
      /about:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/about-contentpage
        hst:lastmodified: 2017-06-27T09:50:18.998-07:00
        hst:pagetitle: About
