definitions:
  config:
    /hst:hst/hst:configurations/gogreen/hst:workspace/hst:sitemenus:
      jcr:primaryType: hst:sitemenus
      /main:
        jcr:primaryType: hst:sitemenu
        hst:lastmodified: 2017-06-27T10:16:12.278-07:00
        /Home:
          jcr:primaryType: hst:sitemenuitem
          hst:referencesitemapitem: root
          hst:repobased: false
        /News:
          jcr:primaryType: hst:sitemenuitem
          hst:referencesitemapitem: news
          hst:repobased: false
        /About:
          jcr:primaryType: hst:sitemenuitem
          hst:referencesitemapitem: content/about.html
          hst:repobased: false
